config/routes.rb
Glassevents::Application.routes.draw do

  # root to "/main_page/#index"

  resources :users, only: [:new, :create, :show]

  resource :session

  root 'events#index'

  resources :services

  resources :admins do
  	member do
  		post 'promote'
  	end
    member do
      post 'demote'
    end
  end

  resources :quotes do
    member do
      post 'choose'
    end
  end

end

app/models/quote.rb
class Quote < ActiveRecord::Base
	# validates :provider, :price, :user_id, :service_id
	
	belongs_to :user
	belongs_to :service
end

app/models/service.rb
class Service < ActiveRecord::Base
	validates :service_name, presence: true
	has_many :quotes
end

app/models/user.rb
class User < ActiveRecord::Base
  validates :email, presence: true, uniqueness: true
  validates :first_name, presence: true
  validates :last_name, presence: true
    
  has_secure_password

  has_many :quotes
end

app/controllers/admins_controller.rb
class AdminsController < ApplicationController

	before_action :set_user, only: [:show, :demote, :promote]
	before_action :authenticated!, :authorized!, only: [:new]

	def index
		@users = User.all
	end

	def show
		@users = User.find(session[:user_id])
		
		if @user.admin == false 
			redirect_to admins_path 
		end
	end

	def new

	end

	def promote
		@user.admin = true
		@user.save
		redirect_to new_admin_path
	end

	def demote
		@user.admin = false
		@user.save
		redirect_to new_admin_path
	end

	private

	def authorized!
		@user = User.find(session[:user_id])
    	unless @user.owner == true
    		redirect_to admins_path(session[:user_id])
    	end
  	end
	
	def set_user
    	@user = User.find(params[:id])
  	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  include SessionsHelper
end

app/controllers/events_controller.rb
class EventsController < ApplicationController

	def index
	end

end

app/controllers/quotes_controller.rb
class QuotesController < ApplicationController

	def show
		@quote = Quote.find(params[:id])
		@service = Service.find(@quote.service_id)
	end

	def index
	end

	def new
		@quote = Quote.new
	end

	def create
		@quote = Quote.new(quote_params)
		@quote.user_id = session[:user_id]
		if @quote.save
      		redirect_to user_path(session[:user_id])
    	else
      		render :new
    	end
	end

	def choose
		@quote = Quote.find(params[:id])
		@quote.chosen = true
		@quote.save
		redirect_to user_path(session[:user_id])
	end

	private
	def quote_params
		params.require(:quote).permit(:provider, :service_id, :price, :info)
	end
end

app/controllers/services_controller.rb
class ServicesController < ApplicationController
	before_action :set_user, :authorized!, only: [:create, :new]

	def new
		@service = Service.new
	end

	def create
		@service = Service.new(service_params)

		if @service.save
      		redirect_to service_path(@service.id)
    	else
      		render :new
    	end 
	end

	def show
		@service = Service.find(params[:id])
	end

	def index
		@services = Service.all
	end


	private

	def service_params
		params.require(:service).permit(:service_name)
	end

	def authorized!
		unless @user.admin == true
			redirect_to services_path
		end
	end

	def set_user
    	@user = User.find(session[:user_id])
  	end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    render :new
  end

  def create
    # authenticate that user/pass combo is legit
    user = User.find_by(email: params[:email])

    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to user_path(user)
    else
      redirect_to new_session_path
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to(new_session_path)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	before_action :set_user, :authenticated!, :authorized!, except: [:new, :create] 

	def new
		@user = User.new
	end

	def create
		@user = User.new(user_params)

		if @user.save
      		redirect_to user_path(@user)
    	else
      		render :new
    	end 
	end

	def show
		# @user = User.find(params[:id])
	end

	private
	def user_params
		params.require(:user).permit(:email, :password, :password_confirmation, :first_name, :last_name)
	end

	def authorized!
    	unless @user.id == session[:user_id]
    		redirect_to user_path(session[:user_id])
    	end
  	end
	
	def set_user
    	@user = User.find(params[:id])
  	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def logged_in?
    session[:user_id].present?
  end

  def authenticated!
    unless logged_in?
      redirect_to new_session_path
    end
  end

  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end
end

app/views/admins/index.html.erb
<% if User.find(session[:user_id])[:owner] == true %>
	<%= link_to "Manage Administrators", new_admin_path %><br><br>
<% end %>

<% @users.each do |u|%>
	<% if u[:admin] == true %>
		 <li><%= link_to "#{u[:first_name]} #{u[:last_name]}", admin_path(u[:id]) %></li>
	<% end %>
<% end %>
<br>
<%= link_to "User Pannel", user_path(session[:user_id]) %>

app/views/admins/new.html.erb
<h1>Admin Management</h1>
<table>
	<tr><td>User</td><td>Admin?</td></tr>
	<% users = User.all %>
	<% users.each do |u| %>
	<tr>
		<td><%= u[:first_name] %> <%= u[:last_name] %></td>
		<td><%= u[:admin] %></td>
		<td id="button">
			<% if u[:admin] == false %>
				<%= button_to "Promote!", promote_admin_path(u[:id]), method: "post" %>
			<% else %>
				<%= button_to "Demote!", demote_admin_path(u[:id]), method: "post" %>
			<% end %>
		</td>
	</tr>
<% end %>
</table>

app/views/admins/show.html.erb
Admin info page <%= @user[:first_name] %>
<BR>
<%= link_to "User Pannel", user_path(session[:user_id]) %>
<%= link_to "Return to Admins", admins_path %>

app/views/events/index.html.erb
<h1>GlassEvents group event planning</h1>

<p>GlassEvents is a tool to add transparency to the process for a group of people to plan an event.   This demo is setup with and example class reunion.  Everyone attending the reunion is able to sign up and view all planning activity, allowing each attendee to see who is doing the work of organizing the event, and what the event will really cost.</p> 

<p>The app features a custom, multi-level user authentication system.  The event creator can promote any user to the admin level, and demote any admin back to a regular user.  The event creator is also, currently, the only user who can select a quote for a given service as the selected provider for the event.</p>

<p>Any administrator can add a new service to the event.  They can also add as many quote as they please to any service.</p>

<p>Once a quote has been selected by the event creator, the user panel will update the service to show a quote has been chosen, and it's price.</p>

<p>This is the first Ruby on Rails project that I created during my 12 week intensive web development course at General Assembly.  Please <%= mail_to "justinkemmerer@gmail.com", "email", subject: "GlassEvents"  %> me with any feedback or questions you may have.</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<!-- paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/ -->
<!--[if lt IE 7 ]> <html class="ie6" lang="en"> <![endif]-->
<!--[if IE 7 ]>    <html class="ie7" lang="en"> <![endif]-->
<!--[if IE 8 ]>    <html class="ie8" lang="en"> <![endif]-->
<!--[if IE 9 ]>    <html class="ie9" lang="en"> <![endif]-->
<!--[if (gt IE 9)|!(IE)]><!--> <html lang="en"> <!--<![endif]-->
  <head>
  	<meta charset="utf-8" />

  	<!-- Uncomment to make IE8 render like IE7 -->
  	<!-- <meta http-equiv="X-UA-Compatible" content="IE=7" /> -->

  	<!-- Set the viewport width to device width for mobile -->
  	<meta name="viewport" content="width=device-width, initial-scale=1.0" />

  	<title><%= content_for?(:title) ? yield(:title) : "Glass Events" %></title>

  	<%= stylesheet_link_tag    "style" %>
    <%= stylesheet_link_tag    "application" %>
  	<%= javascript_include_tag "vendor/custom.modernizr" %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <nav>
      <% if logged_in? %>
        <ul>
          <li><%= link_to 'Logout', session_path, :method => :delete %></li>
        </ul>
      <% else %>
        <%= link_to "Log in", new_session_path %> | 
        <%= link_to "Sign Up", new_user_path %>
      <% end %>
    </nav>

    <%= yield %>

    
    <%= javascript_include_tag "application" %>
  </body>
</html>

app/views/quotes/index.html.erb
quotes index

app/views/quotes/new.html.erb
new quote

<% unless @quote.errors.none? %>
  <% @quote.errors.full_messages.each do |msg| %>
    <%= msg %>
  <% end %>
<% end %>


<%= form_for @quote do |f| %>
	<%= f.label :provider %>
	<%= f.text_field :provider %>

	<%= f.label :price %>
	<%= f.number_field :price %>

	<%= f.label :info %>
	<%= f.text_field :info %>

	<!-- drop down to select services, selected service needs to fill the foreign key on create -->
	<%= collection_select :quote, :service_id, Service.all, :id, :service_name %>

	<!-- grab user id to fill foreign key on create -->
	<%= f.submit => "drop_down" %>

<% end %>

app/views/quotes/new2.html.erb
new quote

<% unless @quote.errors.none? %>
  <% @quote.errors.full_messages.each do |msg| %>
    <%= msg %>
  <% end %>
<% end %>

<%= form_for @quote do |f| %>
	<%= f.label  %>
	<%=  %>

app/views/quotes/show.html.erb
<h1><%= @service.service_name %>: <%= @quote.provider %></h1>

add rest of quotes details

app/views/services/index.html.erb
<% @services.each do |s|%>
<li><%= link_to "#{s.service_name}", service_path(s[:id]) %></li>
<% end %>
<br>

<% if User.find(session[:user_id])[:admin] == true %>
	<%= link_to "Add a service", new_service_path %><br><br>
<% end %>

<%= link_to "Return to User Pannel", user_path(session[:user_id]) %>

app/views/services/new.html.erb
<%= form_for @service do |f| %>
	<%= f.label :service_name %>
	<%= f.text_field :service_name %>

	<%= f.submit %>
<% end %>
<%= link_to "Return to Services", services_path %> 
<%= link_to "Return to User Panel", user_path(session[:user_id]) %> 

app/views/services/show.html.erb
<% service = Service.find(params[:id]) %>
<h1><%= service[:service_name] %></h1>

<p>insert the service info here</p>

<section class="quotes">
	<h4>Quotes:</h4>	

	<% quotes = Quote.where(service_id:service.id) %>
	<table>
		<tr>
			<td>Provider</td>
			<td>Price</td>
			<td>Info</td>
			<td>Creater</td>
		</tr>
		<% quotes.each do |q| %>
			<% creator = User.find(q[:user_id]) %>
			<tr>
				<td><%= q.provider %></td>
				<td><%= q.price %></td>
				<td><%= q.info %></td>
				<td><%= creator.first_name %> <%= creator.last_name %></td>
				
				<% if User.find(session[:user_id])[:owner] == true %>
					<% chosen = Quote.find_by_service_id_and_chosen(service.id, true) %>
					<% if chosen == nil %>
						<td id="button">
							<%= button_to "Choose provider!", choose_quote_path(q[:id]), method: "post" %>
						</td>
					<% end %>
				<% end %>
			</tr>
		<% end %>
	</table>
</section>

<% if User.find(session[:user_id])[:admin] == true %>
	<%= link_to "Add a quote", new_quote_path %><br><br>
<% end %>

<br>
<%= link_to "Return to User Pannel", user_path(session[:user_id]) %>

app/views/users/_form.html.erb
<% unless @user.errors.none? %>
  <% @user.errors.full_messages.each do |msg| %>
    <%= msg %>
  <% end %>
<% end %>

<%= form_for @user do |f| %>
  <%= f.label :first_name %>
  <%= f.text_field :first_name %>

  <%= f.label :last_name %>
  <%= f.text_field :last_name %>

  <%= f.label :email %>
  <%= f.email_field :email %>

  <%= f.label :password %>
  <%= f.password_field :password %>

  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation %>

  <%= f.submit %>
<% end %>

app/views/users/new.html.erb
<h1>Create Account</h1>

<%= render 'form' %>
<%= link_to "Home", root_path %>
<%= link_to "Log in", new_session_path %>

app/views/users/show.html.erb
<h1><%= @user.first_name %> <%= @user.last_name %></h1>

<p>
	<%= @user.email %><br>
	<% if @user.admin == true %>
		You are an admin!
	<% end %>
</p>



<div class="services">
	<% services = Service.all %>
	<% total = 0 %>
	<table>
		<tr><td class="table_title">Services</td></tr>
		<tr class="column_names">
			<td>Service Name</td>
			<td>Quote #</td>
			<td>Quote Chosen?</td>
			<td>Price</td>
		</tr>
		<% services.each do |s| %>
			<% c = "No" %>
			<% chosen = Quote.find_by_service_id_and_chosen(s.id, true) %>
			<% if chosen != nil %>
				<% c = "Yes" %>
			<% end %>
			<% count = Quote.where(service_id: s.id).count %>

			<tr>
				<td><%= link_to "#{s.service_name}", service_path(s[:id]) %></td>
				<td><%= count %></td>
				<td><%= c %></td>
				<td>
					<% if c == "Yes" %>
						$ <%= chosen.price %>
						<% total += chosen.price %>
					<% end %>
				</td>
			</tr>
		<% end %>
		<tr><td class="total">Total: $ <%= total %></td></tr>
		<% if User.find(session[:user_id])[:admin] == true %>
			<tr><td><%= link_to "Add a service", new_service_path %></td></tr>
		<% end %>
	</table>
</div>



<div class="admins">
	<% users = User.all %>
	<table>
		<tr><td class="table_title">Admins</td></tr>
		<tr class="column_names">
			<td>Name</td>
			<td>Quotes Added</td>
		</tr>
		<% users.each do |user| %>
			<% count = Quote.where(user_id: user.id).count %>
			<% if user[:admin] == true %>
	    		<tr>
	    			<td><%= link_to "#{user[:first_name]} #{user[:last_name]}", admin_path(user[:id]) %></td>
	    			<td><%= count %></td>
	    		</tr>

	    	<% end %>
		<% end %>	
	</table>
</div>